---
user_groups:
  - sudo
  - wheel
  - docker

users:
  - { name: lsio, groups: sudo,wheel,docker, sshkeys: linuxserver.keys}
  - { name: ironicbadger, groups: docker, sshkeys: ironicbadger.keys}
  - { name: s7ark, groups: docker, sshkeys: s7ark.keys}
